-- AlterTable
ALTER TABLE "Prodi" ALTER COLUMN "deskripsi" SET DATA TYPE TEXT,
ALTER COLUMN "visi_misi" SET DATA TYPE TEXT,
ALTER COLUMN "sejarah" SET DATA TYPE TEXT,
ALTER COLUMN "info_lainnya" SET DATA TYPE TEXT;
